const CONSTANTS = {
  ROUTES: {
    START_PAGE: "START_PAGE",
    PROCESSING_PAGE: "PROCESSING_PAGE",
    DASHBOARD_PAGE: "DASHBOARD_PAGE",
    SETTINGS_PAGE: "SETTINGS_PAGE",
  },
};

export default CONSTANTS;
