const FE_EVENTS = {
  UPDATE_IMAGES: "UPDATE_IMAGES",
  UPDATE_IMAGES_WITH_LOCATION: "UPDATE_IMAGES_WITH_LOCATION",
  UPDATE_TASK: "UPDATE_TASK",
  SET_ROUTE: "SET_ROUTE",
  RESET_STATE: "RESET_STATE",
};

const BE_EVENTS = {
  CREATE_PROJECT: "CREATE_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
};

module.exports = {
  FE_EVENTS,
  BE_EVENTS,
};
