name: CI
on:
  - pull_request

jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14
    steps:
      # Checkout repo
      - uses: actions/checkout@v2

      # Set node version
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.0"

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test:ci
